import base64
from elevenlabs import VoiceSettings
from elevenlabs.client import ElevenLabs
from yumi.core.config import settings

class YumiSpeaker:
    def __init__(self):
        # Initialize client
        self.client = ElevenLabs(api_key=settings.elevenlabs_api_key)
        
        # Constants for requested voice
        self.model_id = "eleven_multilingual_v2"
        self.voice_id = "HEhcSPjZtkJJ6iMEEKLW" # Adam pre-made voice

    def speak(self, text: str, play_local: bool = False):
        """
        Synthesizes text, optionally plays it locally, and returns the base64 encoded mp3 bytes for the frontend, along with audio duration.
        """
        if not text:
            return None, 0.0

        print(f"Synthesizing voice with ElevenLabs...")
        try:
            # Convert text to speech
            response_chunks = self.client.text_to_speech.convert(
                voice_id=self.voice_id,
                output_format="mp3_22050_32",
                text=text,
                model_id=self.model_id,
                voice_settings=VoiceSettings(
                    stability=0.0,
                    similarity_boost=1.0,
                    style=0.0,
                    use_speaker_boost=True,
                ),
            )
            
            # Read all generated bytes
            audio_data = b"".join([chunk for chunk in response_chunks if chunk])
            
            # For mp3_22050_32 (32kbps constant bitrate), duration is roughly len(bytes) / 4000
            duration = len(audio_data) / 4000.0
            
            # We purposely do not support play_local for the mp3 format yet to avoid heavy dependencies,
            # so we just ignore the `play_local` parameter. The frontend will play the audio.
            if play_local:
                print("Warning: Local playback for ElevenLabs mp3 is not natively supported in this script. Audio will only play on the frontend.")
            
            # Encode raw wave bytes for WebSockets transmission
            audio_base64 = base64.b64encode(audio_data).decode('utf-8')
            return audio_base64, duration
            
        except Exception as e:
            print(f"Error speaking response: {e}")
            return None, 0.0
