from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from yumi.agent.llm import agent
from yumi.agent.personality_manager import personality_manager

def check_personality_switch(user_input: str) -> tuple[bool, str | None]:
    """Check if user wants to switch personality. Returns (is_switch, new_personality)."""
    user_input_lower = user_input.lower().strip()
    
    personalities = personality_manager.list_personalities()
    
    # Check for personality switch commands
    for personality in personalities:
        if user_input_lower in [f"switch to {personality}", f"be {personality}", f"become {personality}", personality]:
            return True, personality
    
    return False, None

def chat_node(state):
    user_input = state["input"]
    history = state.get("messages", [])

    # 1. Check for personality switch
    is_switch, new_personality = check_personality_switch(user_input)
    if is_switch:
        from yumi.core.global_config import update_global_config
        update_global_config("PERSONALITY", new_personality)
        # We rewrite the user input so the LLM explicitly acknowledges the switch naturally
        user_input = f"I want you to become {new_personality}. Acknowledge this personality switch warmly in your new style."

    # 2. Inject current personality as SystemMessage on EVERY turn
    # This solves the "Broken Personality Persistence" bug by ensuring
    # the LLM always has the correct prompt even after a switch.
    current_personality_prompt = personality_manager.get_current_personality_prompt()
    
    # Add an explicit instruction to prevent tool-calling hallucinations where the LLM tries
    # to output its final structured response at the same time it calls a data-fetching tool.
    system_instruction = (
        current_personality_prompt + 
        "\n\nCRITICAL INSTRUCTION: If you need to use a tool to get information (like checking the time), "
        "you MUST ONLY call that tool and wait for the result. Do NOT generate your final YumiResponse "
        "or answer until you have received the tool's output."
    )
    
    system_message = SystemMessage(content=system_instruction)

    # 3. Prepare the input payload
    new_human_message = HumanMessage(content=user_input)
    input_messages = [system_message] + history + [new_human_message]

    print(f"DEBUG: Invoking agent with {len(input_messages)} messages (including system prompt).")

    # 4. Invoke the unified agent (handles tools & structured output natively)
    # This solves the "Redundant LLM Calls" bottleneck.
    result = agent.invoke({"messages": input_messages})

    # Extract the structured response and the new messages generated by the agent
    structured_response = result.get("structured_response")
    
    if structured_response is None:
        # Fallback in case structured output fails
        print("ERROR: structured_response was None. Falling back to default.")
        class Fallback:
            pass
        structured_response = Fallback()
        structured_response.response_text = "I'm having trouble processing that right now."
        structured_response.expression = "sad"
        structured_response.motion = "idle"

    # The agent returns all messages (including what we gave it).
    # We only want to return the newly generated messages to be appended to state history.
    # The newly generated messages are everything after our `input_messages`.
    
    # Wait, the history in `MainState` doesn't have the current `user_input` yet.
    # So we must return the `new_human_message` PLUS whatever the agent generated.
    # Wait, in the older version, we returned the HumanMessage and AIMessage.
    # Because `MainState` uses `add_messages` reducer, returning a list of messages appends them.
    # However, if the `new_agent_messages` contains the ToolMessage with the structured response,
    # we don't necessarily want that raw ToolMessage cluttering the LLM's future context as an AI turn.
    # Let's see... if it used tools, we want the Tool history. If it just structured the output, 
    # it generates an AIMessage with a tool_call, and a ToolMessage with the structured JSON.
    # Feeding this back to the LLM next turn might confuse it because the "final answer" is in a ToolMessage.
    
    # LangChain's `create_agent` docs state that when using structured output via tools, 
    # the structured data is captured in `structured_response`.
    # It's cleaner to just append a standard AIMessage with the text to the history, 
    # discarding the complex tool-call trace of the structured output tool itself.
    # If the agent used OTHER tools (like get_time), we *do* want those.
    # For now, to keep history clean and avoid LLM confusion with its own structured output tool calls:
    
    messages_to_append = [new_human_message, AIMessage(content=structured_response.response_text)]

    return {
        "response": structured_response.response_text,
        "expression": getattr(structured_response, 'expression', 'normal'),
        "motion": getattr(structured_response, 'motion', 'idle'),
        "messages": messages_to_append
    }
