from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from yumi.agent.llm import agent, base_llm, YumiResponse
from yumi.agent.personality_manager import personality_manager

def check_personality_switch(user_input: str) -> tuple[bool, str | None]:
    """Check if user wants to switch personality. Returns (is_switch, new_personality)."""
    user_input_lower = user_input.lower().strip()
    
    personalities = personality_manager.list_personalities()
    
    # Check for personality switch commands
    for personality in personalities:
        if user_input_lower in [f"switch to {personality}", f"be {personality}", f"become {personality}", personality]:
            return True, personality
    
    return False, None

def chat_node(state):
    user_input = state["input"]
    history = state.get("messages", [])

    # 1. Check for personality switch
    is_switch, new_personality = check_personality_switch(user_input)
    if is_switch:
        from yumi.core.global_config import update_global_config
        update_global_config("PERSONALITY", new_personality)
        # We rewrite the user input so the LLM explicitly acknowledges the switch naturally
        user_input = f"I want you to become {new_personality}. Acknowledge this personality switch warmly in your new style."

    # 2. Inject current personality as SystemMessage on EVERY turn
    current_personality_prompt = personality_manager.get_current_personality_prompt()
    
    system_instruction = (
        current_personality_prompt + 
        "\n\nAnswer the user directly and concisely. If you need to use a tool, use it first."
    )
    
    system_message = SystemMessage(content=system_instruction)

    # 3. Prepare the input payload for the ReAct Agent
    new_human_message = HumanMessage(content=user_input)
    input_messages = [system_message] + history + [new_human_message]

    print(f"DEBUG: Invoking agent with {len(input_messages)} messages (including system prompt).")

    try:
        # 4. Invoke the ReAct agent
        # This handles reasoning, tool execution, and returns a final response string.
        result = agent.invoke({"messages": input_messages})
        
        # Extract the final textual response generated by the agent
        final_message = result["messages"][-1].content
        new_agent_messages = result["messages"][len(input_messages):]

    except Exception as e:
        print(f"Agent Loop Error: {e}")
        final_message = "I'm having trouble thinking right now."
        new_agent_messages = [AIMessage(content=final_message)]

    try:
        # 5. Extract Structured Output (Expression/Motion) from the final response
        # We do this as a separate, safe step to prevent tool-calling conflicts in Groq
        struct_parser = base_llm.with_structured_output(YumiResponse)
        structured_response = struct_parser.invoke(
            [SystemMessage(content="Extract the appropriate expression and motion for the following response."),
             HumanMessage(content=final_message)]
        )
    except Exception as e:
        print(f"Structured Output Error: {e}")
        class Fallback:
            pass
        structured_response = Fallback()
        structured_response.response_text = final_message
        structured_response.expression = "sad"
        structured_response.motion = "idle"

    # To keep history clean, we just append the user input and the final AI text response
    # (Optional: If we want tool history in LangGraph memory, we would append `new_agent_messages`)
    messages_to_append = [new_human_message, AIMessage(content=final_message)]

    return {
        "response": final_message, # Use the raw response text from the agent
        "expression": getattr(structured_response, 'expression', 'normal'),
        "motion": getattr(structured_response, 'motion', 'idle'),
        "messages": messages_to_append
    }
